version: '3.8'

services:
  
  app:
    image: node:slim
    depends_on:
      - db
    volumes:
      - ./:/usr/src/project
    environment:
      - NODE_ENV=production
      - docker_db=db
    working_dir: /usr/src/project
    command: /bin/sh -c "npm i && npm run start" # not works: npm i && npm run start and not support bash
    ports:
      - "7001:7001"

  db:
    image: mongo # 镜像:版本
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root # 默认开启授权，并创建超管用户 mongo -u godis -p godis@admin --authenticationDatabase admin
      - MONGO_INITDB_ROOT_PASSWORD=123456 # 超管密码
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017:27017"
    restart: always
    networks:
      - mybridge

networks:
  mybridge: